/// Returns Bible book names, common abbreviations, spoken forms, and theological terms
/// for use as Deepgram keyword boosting.
#[allow(clippy::too_many_lines)]
pub fn bible_keyterms() -> Vec<String> {
    let mut terms: Vec<String> = Vec::new();

    // 66 Bible book names
    let books = [
        "Genesis",
        "Exodus",
        "Leviticus",
        "Numbers",
        "Deuteronomy",
        "Joshua",
        "Judges",
        "Ruth",
        "1 Samuel",
        "2 Samuel",
        "1 Kings",
        "2 Kings",
        "1 Chronicles",
        "2 Chronicles",
        "Ezra",
        "Nehemiah",
        "Esther",
        "Job",
        "Psalms",
        "Proverbs",
        "Ecclesiastes",
        "Song of Solomon",
        "Isaiah",
        "Jeremiah",
        "Lamentations",
        "Ezekiel",
        "Daniel",
        "Hosea",
        "Joel",
        "Amos",
        "Obadiah",
        "Jonah",
        "Micah",
        "Nahum",
        "Habakkuk",
        "Zephaniah",
        "Haggai",
        "Zechariah",
        "Malachi",
        "Matthew",
        "Mark",
        "Luke",
        "John",
        "Acts",
        "Romans",
        "1 Corinthians",
        "2 Corinthians",
        "Galatians",
        "Ephesians",
        "Philippians",
        "Colossians",
        "1 Thessalonians",
        "2 Thessalonians",
        "1 Timothy",
        "2 Timothy",
        "Titus",
        "Philemon",
        "Hebrews",
        "James",
        "1 Peter",
        "2 Peter",
        "1 John",
        "2 John",
        "3 John",
        "Jude",
        "Revelation",
    ];
    terms.extend(books.iter().map(ToString::to_string));

    // Nobody ever says "Open to 1 Cor"
    // Spoken reference cues and sermon language.
    // These improve recognition of Bible references in live speech.
    let reference_terms = [
        // Reference structure
        "chapter",
        "verse",
        "verses",
        "scripture",
        "scriptures",
        "passage",
        "text",
        "reading",
        "book",
        "open to",
        "turn to",
        "reading from",
        "next verse",
        // Spoken numbering
        "first",
        "second",
        "third",
        // Reference transitions
        "chapter one",
        "chapter two",
        "chapter three",
        "verse one",
        "verse two",
        "verse three",
        // Common sermon phrases
        "the Bible says",
        "the scripture says",
        "thus says the Lord",
        "let us read",
        "our text",
        "the word of God",
        // Bible-specific nouns
        "psalm",
        "psalms",
        "gospel",
        "epistle",
        "prophecy",
        // numerals
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "eleven",
        "twelve",
        "thirteen",
        "fourteen",
        "fifteen",
        "sixteen",
        "seventeen",
        "eighteen",
        "nineteen",
        "twenty",
        "thirty",
        "forty",
        "fifty",
        "sixty",
        "seventy",
        "eighty",
        "ninety",
        "hundred",
    ];
    terms.extend(reference_terms.iter().map(ToString::to_string));

    // Spoken forms
    let spoken = [
        "First Samuel",
        "Second Samuel",
        "First Kings",
        "Second Kings",
        "First Chronicles",
        "Second Chronicles",
        "First Corinthians",
        "Second Corinthians",
        "First Thessalonians",
        "Second Thessalonians",
        "First Timothy",
        "Second Timothy",
        "First Peter",
        "Second Peter",
        "First John",
        "Second John",
        "Third John",
        "Song of Songs",
    ];
    terms.extend(spoken.iter().map(ToString::to_string));

    terms
}
